# Map of countries -> emoji flags
# This covers all of the countries that have hosted an F1 race,
# and every F1 driver nationality.
Argentina                = "🇦🇷"
Australia                = "🇦🇺"
Austria                  = "🇦🇹"
Azerbaijan               = "🇦🇿"
Bahrain                  = "🇧🇭"
Belgium                  = "🇧🇪"
Brazil                   = "🇧🇷"
Canada                   = "🇨🇦"
Chile                    = "🇨🇱"
China                    = "🇨🇳"
Colombia                 = "🇨🇴"
"Czech Republic"         = "🇨🇿"
Denmark                  = "🇩🇰"
Netherlands              = "🇳🇱"
Finland                  = "🇫🇮"
France                   = "🇫🇷"
Germany                  = "🇩🇪"
Hungary                  = "🇭🇺"
India                    = "🇮🇳"
Indonesia                = "🇮🇩"
Ireland                  = "🇮🇪"
Italy                    = "🇮🇹"
Japan                    = "🇯🇵"
Liechtenstein            = "🇱🇮"
Malaysia                 = "🇲🇾"
Mexico                   = "🇲🇽"
Monaco                   = "🇲🇨"
Morocco                  = "🇲🇦"
"New Zealand"            = "🇳🇿"
Poland                   = "🇵🇱"
Portugal                 = "🇵🇹"
Qatar                    = "🇶🇦"
Rhodesia                 = "🇿🇼"  # Use Zimbabwe flag, no Rhodesian emoji.
Russia                   = "🇷🇺"
"Saudi Arabia"           = "🇸🇦"
Singapore                = "🇸🇬"
"South Africa"           = "🇿🇦"
"South Korea"            = "🇰🇷"
Spain                    = "🇪🇸"
Sweden                   = "🇸🇪"
Switzerland              = "🇨🇭"
Thailand                 = "🇹🇭"
Turkey                   = "🇹🇷"
UAE                      = "🇦🇪"
UK                       = "🇬🇧"
USA                      = "🇺🇸"
Uruguay                  = "🇺🇾"
Venezuela                = "🇻🇪"
