# Map of F1 driver nationalities -> emoji flags
American = "🇺🇸"
Argentine = "🇦🇷"
Australian = "🇦🇺"
Austrian = "🇦🇹"
Belgian = "🇧🇪"
Brazilian = "🇧🇷"
British = "🇬🇧"
Canadian = "🇨🇦"
Chilean = "🇨🇱"
Chinese = "🇨🇳"
Colombian = "🇨🇴"
Czech = "🇨🇿"
Danish = "🇩🇰"
Dutch = "🇳🇱"
Finnish = "🇫🇮"
French = "🇫🇷"
German = "🇩🇪"
Hungarian = "🇭🇺"
Indian = "🇮🇳"
Indonesian = "🇮🇩"
Irish = "🇮🇪"
Italian = "🇮🇹"
Japanese = "🇯🇵"
Liechtensteiner = "🇱🇮"
Malaysian = "🇲🇾"
Mexican = "🇲🇽"
Monegasque = "🇲🇨"
Moroccan = "🇲🇦"
"New Zealander"= "🇳🇿"
Polish = "🇵🇱"
Portuguese = "🇵🇹"
Rhodesian = "🇿🇼"  # Use Zimbabwe flag, no Rhodesian emoji.
Russian = "🇷🇺"
"South African"= "🇿🇦"
Spanish = "🇪🇸"
Swedish = "🇸🇪"
Swiss = "🇨🇭"
Thai = "🇹🇭"
Uruguayan = "🇺🇾"
Venezuelan = "🇻🇪"

